#DATA
data_root: data
classes: 2
modality: dsa


#MODEL
arch: utnetv2
in_chan: 1
base_chan: 32
conv_block: 'BasicBlock'
conv_num: [2,1,0,0,  0,1,2,2] #[2,1,0,0, 0,1,2,2]
trans_num: [0,1,2,2,  2,1,0,0] #[0,1,2,2, 2,1,0,0]
#num_heads: [4, 4, 4, 4, 4, 4, 4, 4]
num_heads: [1,4,8,16, 8,4,1,1] #[1, 2, 4, 8, 4, 2, 1, 1]
map_size: 8
expansion: 1
fusion_depth: 2
fusion_dim: 512
fusion_heads: 16
proj_type: 'depthwise'
attn_drop: 0.
proj_drop: 0.



#TRAIN
epochs: 40
training_size: [512, 512]    # training crop size
start_epoch: 0

seed: 0
k_fold: 5

optimizer: adamw
base_lr: 0.0005   
betas: [0.9, 0.999]
weight_decay: 0.05  # weight decay of SGD optimizer
weight: [0.5, 1]  # weitght of each class in the loss function
rlt: 1 # relation between CE and Dice loss

scale: 0.3  # scale for data augmentation
rotate: 180 # rotation angle for data augmentation
translate: 0



#VALIDATION
ema: True
ema_alpha: 0.99
val_frequency: 1

#INFERENCE
sliding_window: False
